# Generated by Django 2.1.5 on 2019-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='age',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
