# Generated by Django 2.1.5 on 2019-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0002_auto_20191209_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruduser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
